const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const MONTHS_LONG = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** Frontmatter dates are parsed as UTC midnight; format in UTC so the day never shifts. */
export function formatDate(date: Date, long = false): string {
  const month = (long ? MONTHS_LONG : MONTHS)[date.getUTCMonth()];
  return `${month} ${date.getUTCDate()}, ${date.getUTCFullYear()}`;
}

export function isoDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/** Certificate images have a 900px thumbnail generated by scripts/thumbs.mjs. */
export function thumb(image: string): string {
  const i = image.lastIndexOf("/");
  return encodeURI(`${image.slice(0, i)}/thumbs/${image.slice(i + 1)}`);
}
